# Generated by Django 5.1.4 on 2025-02-09 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchMGR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
