# Generated by Django 5.1.4 on 2025-02-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punchMGR', '0002_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='inspmgr_customuser',
        ),
    ]
